### PR TITLE
fix: Fixes #130. Mobile menu styling

### LINKED ISSUE #130: Menu Popup on devices with resolution less than 720px ,bg color looks little aweful, need to optimise that

### PR DESCRIPTION
**Pull request by ltfschoen**
* Change background colour to black
* Change link text colour to white
* Prevent gap from being shown at bottom of mobile menu by stretching the mobile menu popup so its height extends to the bottom of any screen (including Pixel 2 XL)
* Prevent mobile menu items (e.g. Home) being hidden behind navbar on small screen heights (e.g. iPhone4 landscape of 320px height)
* Note: Mobile menu appears on devices <576px wide

### CODE REVIEW

File: components/common/Header.js [hunk 1]
```diff
@@ -232,15 +232,23 @@ class Header extends Component {
...
                 ...defaultStyle,
-                ...transitionStyles[state]
+                ...transitionStyles[state],
+                // Prevent gap being shown at bottom of mobile menu
+                top: '1em'
               }}
             >
-              <div className="position-absolute top-0 left-0 right-0 h-100vh mobile-menu-inner bg-brand700 d-flex flex-column justify-content-center">
+              <div
+                className="position-absolute top-0 left-0 right-0 h-100vh mobile-menu-inner bg-black700 d-flex flex-column justify-content-center"
```
Comment (ltfschoen) [inline components/common/Header.js:241]: don't need top-0
```suggestion
                className="position-absolute left-0 right-0 h-100vh mobile-menu-inner bg-black700 d-flex flex-column justify-content-center"
```

File: components/common/Header.js [hunk 2]
```diff
@@ -232,15 +232,23 @@ class Header extends Component {
               className="d-sm-none position-fixed top-0 left-0 right-0 overflow-hidden"
```
Comment (ltfschoen) [inline components/common/Header.js:232]: remove unnecessary top margin
```suggestion
              className="d-sm-none position-fixed left-0 right-0 overflow-hidden"
```

**Comment by robbieaverill** [comment]
Looks good, thanks for the pull request!

There's still 1 or 2 pixels gap at the bottom of the screen for me (Chrome emulating an iPhone). We can probably update the classes used in that view and replace with something like `h-screen w-screen` to fix these issues.

**Comment by robbieaverill** [comment]
This is better than it was, so merging. Thanks for the contribution @ltfschoen 🙂
