### PR TITLE
Fix Link components to all contain anchor child tags, fix link styling

### LINKED ISSUE #221: React warning for expected <a> tag in <Link> component
image

This is on every page when running in dev mode. There are a number of places where we use the Next.js `<Link>` component without a direct `<a>` as a child, but unsure which one is causing this error. I tried commenting some out but couldn't find the problem quickly.

### PR DESCRIPTION
**Pull request by jaepass**
Fixes #221

### CODE REVIEW

File: components/products/CategoryList.js [hunk 1]
```diff
@@ -13,12 +13,14 @@ export default connect(({ categories }) => ({ categories }))(
...
-              style={{ 'fontWeight': current === category.id && 'bold' }}
-              key={category.id} className="pb-2 cursor-pointer"
-            >
-              { category.name }<sup>{ category.products }</sup>
-            </li>
+            <a className="font-color-black">
+              <li
+                style={{ 'fontWeight': current === category.id && 'bold' }}
+                key={category.id} className="pb-2 cursor-pointer"
+              >
```
Comment (robbieaverill) [inline components/products/CategoryList.js:20]: I think this one needs to have the ul have children that are li, then we can put the Link and a inside the li

Comment (jaepass) [reply components/products/CategoryList.js:20]: Good catch TA!

**Review by robbieaverill — APPROVED** [review]
